config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'notes/create'
  get 'notes/destroy'
  get 'billers/new'
  get 'billers/create'
  get 'billers/destroy'
  resources :collections
  resources :practices
  resources :billers
  root to: 'pages#home'
  devise_for :users
  post 'new_note', to: 'collections#new_note'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biller.rb
class Biller < ApplicationRecord
end

app/models/collection.rb
class Collection < ApplicationRecord
    belongs_to :practice, dependent: :destroy
    has_one_attached :scan
    has_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :collection
end

app/models/practice.rb
class Practice < ApplicationRecord
    has_many :collections
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billers_controller.rb
class BillersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :index]

  def index
    @billers = Biller.all
  end

  def new
    @biller = Biller.new
  end

  def create
    @biller = Biller.new(biller_params)
    if @biller.save
      redirect_to biller_path(@biller)
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @biller = Biller.find(params[:id])
    @biller.destroy
    redirect_to billers_path
  end

  def show
  end

  private

  def biller_params
    params.require(:biller).permit(:company_name, :name, :email, :phone, :amount_owed, :number_of_accounts, :time_outstanding, :industry, :details)
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    if params[:commit]
      if params[:search_type] == "Account Number"
        @collection = Collection.find_by(account_number: params[:search])
        puts @collection
      elsif params[:search_type] == "Last Name"
        @collection = Collection.find_by(lname: params[:search])
        puts @collection
      elsif params[:search_type] == "Date of Birth"
        @collection = Collection.find_by(dob: params[:search])
        puts @collection
      end
    end
  end

  def show
    @practice = Practice.find(@collection.practice_id)
    # @notes = @practice.notes.all.order('created_at DESC')
  end

  def new
    @collection = Collection.new
    @practices = Practice.all.map { |u| [u.code, u.id] }
  end

  def edit
    @practices = Practice.all.map { |u| [u.code, u.id] }
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      @collection.account_number = @collection.id + 1000
      @collection.save
      redirect_to @collection, notice: 'Collection was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def new_note
    new_note = Note.new(collection_id: params[:collection_id], message: params[:message])
    puts new_note.errors.full_messages if !new_note.save
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:account_number, :ssn, :dob, :lname, :fname, :money_due, :money_paid, :practice_id, :total_due, :phone, :phone2, :phone3, :notes, :search, :address, :address2, :city, :state, :zip, :scan)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /practices
  # GET /practices.json
  def index
    if params[:commit]
      @practice = Practice.find_by(code: params[:search])
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)
    if @practice.save
      redirect_to @practice, notice: 'Practice was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def practice_params
      params.require(:practice).permit(:name, :code, :address, :city, :state, :zip, :phone, :dr_type, :search)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billers_helper.rb
module BillersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/billers/_form.html.erb
<%= form_with(model: @biller, local: true) do |form| %>
  <% if @biller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biller.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @biller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-grid">
    <div class="field">
      <%= form.label :company_name, "Company Name" %>
      <%= form.text_field :company_name %>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>



    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>

    <div class="field">
      <%= form.label :amount_owed, "Approximately how much are you collecting?" %>
      <%= form.text_field :amount_owed %>
    </div>

    <div class="field">
      <%= form.label :number_of_accounts, "Approximately how many accounts do you need to be collected on?" %>
      <%= form.text_field :number_of_accounts %>
    </div>

    <div class="field">
      <%= form.label :time_outstanding, "How long, on average, have the debts you need collected been outstanding?" %>
      <%= form.text_field :time_outstanding %>
    </div>

    <div class="field">
      <%= form.label :industry %>
      <%= form.text_field :industry %>
    </div>

    <div class="field">
      <%= form.label :details %>
      <%= form.text_area :details %>
    </div>

    <div class="actions">
      <%= form.submit "Submit Form", :class => "submit-btn" %>
    </div>

  </div>
<% end %>

app/views/billers/_show.html.erb
<% @billers.each do |biller| %>

    <h2 class="new-sect full-grid"><%= biller.company_name %></h2>

    <p>
    <strong>Company Name:</strong>
    <%= biller.company_name %>
    </p>

    <p>
    <strong>Name:</strong>
    <%= biller.name %>
    </p>

    <p>
    <strong>Email:</strong>
    <%= biller.email %>
    </p>

    <p>
    <strong>Phone Number:</strong>
    <%= biller.phone %>
    </p>

    <p>
    <strong>Amount Owed:</strong>
    <%= biller.amount_owed %>
    </p>

    <p>
    <strong>Number of Accounts:</strong>
    <%= biller.number_of_accounts %>
    </p>

    <p>
    <strong>Time Outstanding:</strong>
    <%= biller.time_outstanding %>
    </p>

    <p>
    <strong>Industry:</strong>
    <%= biller.industry %>
    </p>

    <p>
    <strong>Details:</strong>
    <%= biller.details %>
    </p><br>

    <%= link_to 'Delete', biller, method: :delete %></p>
    <div class="break-line-full full-grid"></div>
<% end %>

app/views/billers/index.html.erb
<div class="hero">
  <h2>Biller Applications</h2>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
  <% if @billers.length > 0 %>
    <div class="search-container">
      <%= render 'billers/show' %>
    </div>
  <% else %>
    <h3 class="new-sect">No Biller Applications Active</h3>
    <%= link_to "Back", root_path %>
  <% end %>
</div>

app/views/billers/new.html.erb
<div class="hero"><h2>Let's Work Together</h2></div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
    <p class="new-sect">Please enter the following information</p>
    <div class="break-line"></div>
    <%= render 'form' %>
</div>

app/views/billers/show.html.erb
<div class="hero">
  <h2>Biller's Portal</h2>
</div>>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
    <p class="thanks-msg">Thank you. We'll get back to you within 2 business days.</p>
</div>

app/views/collections/_form.html.erb
<%= form_with(model: @collection, local: true) do |form| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-grid">
    <div class="field">
      <%= form.label :fname, "First Name" %>
      <%= form.text_field :fname %>
    </div>

    <div class="field">
      <%= form.label :lname, "Last Name" %>
      <%= form.text_field :lname %>
    </div>
    
    <div class="field">
      <%= form.label :dob, "Date of Birth" %>
      <%= form.date_field :dob %>
    </div>

    <div class="field">
      <%= form.label :ssn, "Social Security Number" %>
      <%= form.text_field :ssn %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :address2, "Address Line 2" %>
      <%= form.text_field :address2 %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :zip, "Zipcode" %>
      <%= form.text_field :zip %>
    </div>

    <div class="field">
      <%= form.label :money_due %>
      <%= form.text_field :money_due %>
    </div>

    <div class="field">
      <%= form.label :money_paid %>
      <%= form.text_field :money_paid %>
    </div>

    <div class="field">
      <%= form.label :total_due %>
      <%= form.text_field :total_due %>
    </div>

    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>

    <div class="field">
      <%= form.label :phone2 %>
      <%= form.text_field :phone2 %>
    </div>

    <div class="field">
      <%= form.label :phone3 %>
      <%= form.text_field :phone3 %>
    </div>

    <div class="field">
      <%= form.label :practice_id %>
      <%= form.select(:practice_id, options_for_select(@practices)) %>
    </div>

    <div class="field">
      <%= form.label :scan, "Upload Scan" %>
      <%= form.file_field :scan %>
    </div>

    <div class="actions">
      <%= form.submit :class => "submit-btn" %>
    </div>

  </div>
<% end %>

app/views/collections/_show.html.erb
<% if current_user && current_user.admin %>
  <h2 class="new-sect full-grid"><%= link_to @collection.fname + " " + @collection.lname, @collection %></h2>
  <p class="full-grid">Click above for more info and notes.</p>
<% else %>
  <h2 class="new-sect full-grid"><%= @collection.fname + " " + @collection.lname %></h2>
<% end %>
<p>
  <strong>Account number:</strong>
  <%= @collection.account_number %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @collection.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @collection.lname %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @collection.dob %>
</p>

<p>
  <strong>Money due:</strong>
  <%= @collection.money_due %>
</p>

<p>
  <strong>Money paid:</strong>
  <%= @collection.money_paid %>
</p>

<p>
  <strong>Total due:</strong>
  <%= @collection.total_due %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @collection.phone %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @collection.phone2 %>
</p>

<p>
  <strong>Phone3:</strong>
  <%= @collection.phone3 %>
</p>

<p>
  <strong>Practice:</strong>
  <%= @collection.practice.name %>
</p><br>

<% if @collection.scan.attached? %>
  <div class="attached-scan">
  <p><strong>Scan:</strong></p>
    <%= image_tag(@collection.scan, class: "scan-img full-grid") %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div class="hero"><h2>Edit Collection</h2></div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
    <p class="new-sect">Please enter the following information</p>
    <div class="break-line"></div>
    <%= render 'form', collection: @collection %>
</div>

app/views/collections/index.html.erb
<div class="hero">
  <h2>Collections</h2>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
  <div class="search">
    <%= form_with(url: collections_path, method: "get", local: true) do %>
  <p class="new-sect">Search for Collections</p>
      <%= text_field_tag(:search, params[:search]) %>
      <%= select_tag(:search_type, options_for_select(["Account Number", "Last Name", "Date of Birth"])) %>
      <%= submit_tag ("Search") %><br>
    <% end %>
    <% if current_user && current_user.admin %>
      <%#= Show All Button %>
    <% end %>
  </div>
  <div class="break-line"></div>
</div>
  <% if @collection %>
    <div class="search-container">
      <%= render 'collections/show' %>
    </div>
  <% end %>

app/views/collections/new.html.erb
<div class="hero"><h2>New Collection</h2></div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
    <p class="new-sect">Please enter the following information</p>
    <div class="break-line"></div>
    <%= render 'form' %>
</div>

app/views/collections/show.html.erb
<div class="hero"><h2>View Collection</h2></div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
  <h2 class="article-title"><%= @collection.fname + " " + @collection.lname %></h2>
  <a class="page-btn" href="#attached-scan">Scan</a>
  <a class="page-btn" href="#notes-container">Notes</a>
  <div class="text-left">
    <p>
      <strong>Account number:</strong>
      <%= @collection.account_number %>
    </p>

    <p>
      <strong>First Name:</strong>
      <%= @collection.fname %>
    </p>

    <p>
      <strong>Last Name:</strong>
      <%= @collection.lname %>
    </p>

    <p>
      <strong>Social Security Number:</strong>
      <%= @collection.ssn %>
    </p>

    <p>
      <strong>Date of Birth:</strong>
      <%= @collection.dob %>
    </p>

    <p>
      <strong>Money due:</strong>
      <%= @collection.money_due %>
    </p>

    <p>
      <strong>Money paid:</strong>
      <%= @collection.money_paid %>
    </p>

    <p>
      <strong>Total due:</strong>
      <%= @collection.total_due %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @collection.phone %>
    </p>

    <p>
      <strong>Phone2:</strong>
      <%= @collection.phone2 %>
    </p>

    <p>
      <strong>Phone3:</strong>
      <%= @collection.phone3 %>
    </p>

    <p>
      <strong>Practice:</strong>
      <%= @collection.practice.name %>
    </p><br>

    <% if @collection.scan.attached? %>
      <div id="attached-scan">
      <p><strong>Scan:</strong></p>
        <%= image_tag(@collection.scan, class: "scan-img full-grid") %>
      </div>
    <% end %>

    <br><br><%= link_to 'Edit Collection', edit_collection_path(@collection) %>
    <%= link_to 'Back', collections_path %><br><br>

    <% if @collection.notes %>
        <div id="notes-container">
          <div class="note-form">
            <%= form_with(url: '/new_note', method: 'POST') do |f| %>
              <%= f.label :message, "Note:", class: "note-info" %><br>
              <%= f.text_area :message %>
              <%= f.hidden_field :collection_id, value: @collection.id %>
              <%= f.submit %>
            <% end %>
          </div>
      <% @collection.notes.each do |note| %>
          <div class="note">
            <p class="note-info"> <%= note.created_at.strftime("%Y-%m-%d") %> </p>
            <p><%= note.message %></p>
          </div>
      <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollectionWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav-grid short-grid">
      <h2><%= link_to "RJS Billing", root_path, class: "logo" %></h2>
      <div class="mobile-menu">
        <i class="fa fa-bars"></i>
      </div>
      <div class="nav-list hidden-menu">
        <p><%= link_to 'Home', root_path %></p>
        <p><%= link_to 'Find/Pay Bill', collections_path %></p>
        <% if current_user %>
          <p><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
        <% else %>
          <p><%= link_to 'Client Sign In', new_user_session_path %></p>
        <% end %>
        <%= button_tag "GET A QUOTE", :type => 'button', :class => "quote-btn", :onclick => "location.href = '#{new_biller_path()}'" %>
      </div>
    </nav>
    <% if current_user && current_user.admin %>
      <div class="admin-links">
        <p><%= link_to 'Add Practice', new_practice_path %></p>
        <p><%= link_to 'Add Collection', new_collection_path %></p>
        <p><%= link_to 'Search Practices', practices_path %></p>
        <p><%= link_to 'Search Collections', collections_path %></p>
        <p><%= link_to 'Biller Applications', billers_path %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/pages/home.html.erb
<div class="hero">
  <h2>About Us</h2>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<article class="main-content">
  <h2 class="article-title">RJS Billing Services, LLC</h2>
  <div class="break-line"></div>
  <p class="new-sect">Our Mission</p>
  <p>
    Your time is important. With such valued services, your energy shouldn't have to be directed towards collections.
    At RJS Billing, we look foward to recovering and resolving these situations for you. With our team of devoted agents,
    you can be sure our efforts will be persistent towards relieving you of that stress.
  </p>
  <p class="new-sect">Experience</p>
  <p>
    At RJS Billing, you can expect to find a team of highly trained, HIPAA, compliant debt collectors that specialize in 
    medical billing. With over a decade of experience and a refined strategy, we leave both our clients and debtors satisfied.
  </p>
  <p class="new-sect">Determination</p>
  <p>
    We understand that this process is stressful for both the clients and debtors. We make it a point to be thoughtful yet
    persistent so that a resolution can be attained.
  </p>
</article>
<footer>
  <p>This is an attempt to collect a debt, by a debt collector, and any information obtained will be used for that purpose.</p>
  <p>© 2020 RJS Billing, LLC</p>
</footer>

app/views/practices/_form.html.erb
<%= form_with(model: practice, local: true) do |form| %>
  <% if practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-grid">
    <div class="field">
      <%= form.label :name, "Name:" %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :code, "Code:" %>
      <%= form.text_field :code %>
    </div>

    <div class="field">
      <%= form.label :address, "Address:" %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :city, "City:" %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :state, "State:" %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :zip, "Zip:" %>
      <%= form.text_field :zip %>
    </div>

    <div class="field">
      <%= form.label :phone, "Phone:" %>
      <%= form.text_field :phone %>
    </div>

    <div class="field">
      <%= form.label :dr_type, "Type:" %>
      <%= form.text_field :dr_type %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/practices/_show.html.erb
<p>
  <strong>Name:</strong>
  <%= @practice.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @practice.code %>
</p>

<p>
  <strong>Address:</strong>
  <%= @practice.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @practice.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @practice.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @practice.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @practice.phone %>
</p>

<p>
  <strong>Type:</strong>
  <%= @practice.dr_type %>
</p><br>
<div class="break-line-full full-grid"></div>
<div class="practice-collections-list">
<h2>Collections For This Practice</h2>
<p>
<% @practice.collections.each do |c| %>
  <p><%= link_to c.fname + ' ' + c.lname, collection_path(c) %></p>
<% end %>
</p>
</div><br>

<div class="break-line-full full-grid"></div>

<p>
<%= link_to 'Edit Practice', edit_practice_path(@practice) %>
<%= link_to 'New Practice', new_practice_path %></p>

app/views/practices/edit.html.erb
<div class="hero"><h2>Edit Practice</h2></div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="main-content">
    <p class="new-sect">Please enter the following information</p>
    <div class="break-line"></div>
    <%= render 'form', practice: @practice %>
</div>

app/views/practices/index.html.erb
<div class="hero">
  <h2>Practices</h2>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="main-content">
  <div class="search">
    <%= form_with(url: practices_path, method: "get", local: true) do %>
  <p class="new-sect">Search for Practice by Code</p>
      <%= text_field_tag(:search, params[:search]) %><br>
      <%= submit_tag ("Search") %><br>
    <% end %>
    <% if current_user && current_user.admin %>
      <%#= Show All Button %>
    <% end %>
  </div>
  <div class="break-line"></div>
</div>
<% if @practice %>
  <div class="search-container">
    <%= render 'practices/show' %>
  </div>
<% end %>

app/views/practices/new.html.erb
<div class="hero"><h2>New Practice</h2></div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="main-content">
    <p class="new-sect">Please enter the following information</p>
    <div class="break-line"></div>
    <%= render 'form', practice: @practice %>
</div>